name: Run Robocop

on:
  push:
    branches:
      - '[fF]eature/**'
      - '[bBhH][a-zA-Z][a-zA-Z]fix/**'
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    branches:
      - '[fF]eature/**'
      - '[bBhH][a-zA-Z][a-zA-Z]fix/**'
      -  main

jobs:
  build:
    runs-on: ubuntu-24.04
    # continue even if Robocop returns issues and fails step
    continue-on-error: false
    permissions:
      # required for issues to be recorded
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U robotframework-robocop==5.8.1
      - name: Run robocop
        run: python -m robocop --reports all,sarif . -e 0508,0503,0501,0506,0203,0504,0505,1012,0924,0202,0201,0507,0204,0927,0317,0605,0327,0328,0916,0309,1002,0702,0305,1005,0922,0323,0319,0919,0319,1008,1003,0910,0926,0302,0808,1012,0306,1010,1006,1001,0911,0324,0930,0509,1009,1004,0909,0929,0310,0912,0920,0913,0914 -c too-many-calls-in-keyword:max_calls:50 -c line-too-long:line_length:250 || true
        continue-on-error: false
      
      # - name: Upload SARIF file
      #  uses: github/codeql-action/upload-sarif@v3
      #  with:
      #    sarif_file: .sarif.json
      #    category: robocop
